services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./test_api:/test_api
    environment:
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=56776589gl

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=56776589gl